###########################################################
#                                                         #
# Copyright (c)                                           #
#                                                         #
# The Verifiable & Control-Theoretic Robotics (VECTR) Lab #
# University of California, Los Angeles                   #
#                                                         #
# Authors: Kenny J. Chen, Ryan Nemiroff, Brett T. Lopez   #
# Contact: {kennyjchen, ryguyn, btlopez}@ucla.edu         #
#                                                         #
###########################################################

dlio:

  frames:
    odom: odom
    baselink: base_link
    lidar: lidar
    imu: imu

  map:
    waitUntilMove: false
    dense:
      filtered: false
    sparse:
      leafSize: 0.1

  odom:

    gravity: 9.80665
    computeTimeOffset: true

    imu:
      approximateGravity: true
      calibration:
        gyro: true
        accel: true
        time: 3
      bufferSize: 15000

    preprocessing:
      cropBoxFilter:
        size: 1.0
      voxelFilter:
        res: 0.03

    keyframe:
      threshD: 0.5
      threshR: 30.0

    submap:
      keyframe:
        knn: 20
        kcv: 20
        kcc: 20
    gicp:
      minNumPoints: 64
      kCorrespondences: 16
      maxCorrespondenceDistance: 0.7
      maxIterations: 48
      transformationEpsilon: 0.001
      rotationEpsilon: 0.001
      initLambdaFactor: 1e-9

    geo:
      Kp: 5.0
      Kv: 8.0
      Kq: 5.0
      Kab: 5.0
      Kgb: 2.0
      abias_max: 5.0
      gbias_max: 0.5
